### ISSUE TITLE
doesn't build with latest version of ctypes

### ISSUE THREAD

**Issue by UnixJunkie** [whitequark/ocaml-lz4#8] opened 2015-06-18 08:48 UTC

**Comment by yallop** [comment] 2015-06-18 08:59
Could you provide a more detailed description?  For example
* What do you mean by "latest version of ctypes" (e.g. 0.4.1 or master)?
* Which version of ocaml-lz4 are you using?
* What error message do you see?

**Comment by UnixJunkie** [comment] 2015-06-18 09:09
ctypes 0.4.1
the head of the master branch of lz4
https://gist.github.com/UnixJunkie/2f7ebba11dbb51dab044

**Comment by whitequark** [comment] 2015-06-18 16:28
Which ocamlfind version do you have?

**Comment by UnixJunkie** [comment] 2015-06-18 16:44
1.5.5

**Comment by whitequark** [comment] 2015-06-18 16:51
Cannot reproduce with ocamlfind 1.5.5, ctypes 0.4.1, ocaml 4.01.0, lz4 master.

**Comment by UnixJunkie** [comment] 2015-06-18 17:52
I am using ocaml 4.01.0. Not sure if it matters but ...

**Comment by UnixJunkie** [comment] 2015-06-18 17:56
I am using opam 1.2.2 also

**Comment by UnixJunkie** [comment] 2015-06-18 18:01
OK, so to correct the problem on my computer, I need to touch the _oasis file:
-  CCOpt:            -I $pkg_ctypes_stubs/..
+  CCOpt:            -I $pkg_ctypes_stubs/
then the following sequence of commands will build the library:
https://gist.github.com/UnixJunkie/4d253b1b97f8d8936c61

**Comment by whitequark** [comment] 2015-06-18 19:00
I figured it out. You are not using lz4 master. You're using a commit before a4027f006bb8; this is already fixed in master for a long time.

**Closed by whitequark** 2015-06-18 19:00 UTC

**Comment by UnixJunkie** [comment] 2015-06-22 22:02
Can you create a new tag?
I can update the opam package but I would need a tag then.

**Comment by whitequark** [comment] 2015-06-22 22:15
https://github.com/ocaml/opam-repository/pull/4292
